update poc.yaml

diff --git a/.github/workflows/poc.yaml b/.github/workflows/poc.yaml
--- a/.github/workflows/poc.yaml
+++ b/.github/workflows/poc.yaml
@@ -29,11 +29,11 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Requires at least one platform
-        run: exit 1
+        run: echo "::error title=Requires at least one platform::please choose android/ios" && exit 1
         if: ${{ !inputs.android && !inputs.ios }}
 
       - name: Requires at least one environment
-        run: exit 1
+        run: echo "::error title=Requires at least one environment::please choose qa/prod" && exit 1
         if: ${{ !inputs.qa && !inputs.prod }}
 
       - name: Prints 'inputs'
