update poc.yaml

diff --git a/.github/workflows/poc.yaml b/.github/workflows/poc.yaml
--- a/.github/workflows/poc.yaml
+++ b/.github/workflows/poc.yaml
@@ -6,17 +6,21 @@ on:
       android:
         description: 'android'
         required: true
+        default: true
         type: boolean
       ios:
         description: 'ios'
         required: true
+        default: true
         type: boolean
       qa:
         description: 'qa'
+        required: true
         default: true
         type: boolean
       prod:
         description: 'prod'
+        required: true
         default: true
         type: boolean
 
@@ -24,18 +28,6 @@ jobs:
   setup:
     runs-on: ubuntu-latest
     steps:
-      - name: Validate platform
-        if: ${{ !inputs.android && !inputs.ios }}
-        run: |
-          echo "::error title=Requires at least one platform::please choose android/ios"
-          exit 1
-
-      - name: Validate environment
-        if: ${{ !inputs.qa && !inputs.prod }}
-        run: |
-          echo "::error title=Requires at least one environment::please choose qa/prod"
-          exit 1
-
       - name: Print 'inputs'
         env:
           INPUTS_JSON: ${{ toJSON(inputs) }}
@@ -47,6 +39,18 @@ jobs:
           echo '```json' >> $GITHUB_STEP_SUMMARY
           echo $INPUTS_JSON >> $GITHUB_STEP_SUMMARY
           echo '```' >> $GITHUB_STEP_SUMMARY
+
+      - name: Validate platform
+        if: ${{ !inputs.android && !inputs.ios }}
+        run: |
+          echo "::error title=Requires at least one platform::please choose android/ios"
+          exit 1
+
+      - name: Validate environment
+        if: ${{ !inputs.qa && !inputs.prod }}
+        run: |
+          echo "::error title=Requires at least one environment::please choose qa/prod"
+          exit 1
 
   android-qa:
     runs-on: ubuntu-latest
